version: '3'
services:
    docker-example:
        build:
            context: ./
            dockerfile: Dockerfile
        image: docker-example
        ports:
            -   8080:8080
        restart: always
