version: '3'
services:
    apollo-portal:
        image: apolloconfig/apollo-portal
        environment:
            SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/ApolloPortalDB?characterEncoding=utf8"
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root
#            APOLLO_PORTAL_ENVS: dev,pro
#            DEV_META: http://apollo-configservice:8080
#            PRO_META: http://apollo-configservice:8080
        #        volumes:
        #            - /tmp/logs:/opt/logs
        ports:
            - 8070:8070
    apollo-configservice:
        image: apolloconfig/apollo-configservice
        environment:
            SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/ApolloConfigDB?characterEncoding=utf8"
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root
#        volumes:
#            - /tmp/logs:/opt/logs
        ports:
            - 8080:8080
    apollo-adminservice:
        image: apolloconfig/apollo-adminservice
        environment:
            SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/ApolloConfigDB?characterEncoding=utf8"
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root
#        volumes:
#            - /tmp/logs:/opt/logs
        ports:
            - 8090:8090

