# Use root/example as user/password credentials
version: '3'

services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/${MYSQL_VERSION}/etc/mysql/my.cnf:/etc/mysql/my.cnf:rw
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    restart: always
    deploy:
      resources:
        limits:
          memory: 4096M
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 33306:8080