version: '3'
services:
  mysql:
    image: mysql:oracle
#    volumes:
#         - mysql:/var/lib/mysql/
    environment:
#      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=app
    ports:
      - 3306:3306
    command: mysqld
    restart: always
volumes:
    mysql:
