Fversion: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
#      - ./nginx/ca.key:/etc/nginx/ca.key:ro
#      - ./nginx/ca.crt:/etc/nginx/ca.crt:ro
#      - ./nginx/html:/usr/share/nginx/html:ro
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx/conf.d:/etc/nginx/conf.d/
#      - ./nginx/conf.d/ssl.conf:/etc/nginx/conf.d/ssl.conf:ro
#      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
#      - ./nginx/conf.d/gitlab.conf:/etc/nginx/conf.d/gitlab.conf:ro
#      - ./nginx/conf.d/zipkin.conf:/etc/nginx/conf.d/zipkin.conf:ro
#      - ./nginx/conf.d/prometheus.conf:/etc/nginx/conf.d/prometheus.conf:ro
#      - ./nginx/conf.d/grafana.conf:/etc/nginx/conf.d/grafana.conf:ro
#      - ./nginx/conf.d/skywalking.conf:/etc/nginx/conf.d/skywalking.conf:ro
#      - ./nginx/conf.d/nacos.conf:/etc/nginx/conf.d/nacos.conf:ro
      - ./nginx/conf.d/sentinel.conf:/etc/nginx/conf.d/sentinel.conf:ro
      - ./nginx/conf.d/rocketmq.conf:/etc/nginx/conf.d/rocketmq.conf:ro
    ports:
      - 80:80
      - 443:443
    command: [nginx-debug, '-g', 'daemon off;']
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 4096M