version: '3'
services:
    prometheus:
        image: prom/prometheus
        volumes:
          #            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
          #            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        expose:
            - 9090
