version: '2'
services:
    namesrv:
        image: apacherocketmq/rocketmq
        container_name: rmqnamesrv
        ports:
            - 9876:9876
        volumes:
            - rmqnamesrv/logs:/home/rocketmq/logs
        command: sh mqnamesrv
        restart: always
    broker:
        image: apacherocketmq/rocketmq
        container_name: rmqbroker
        ports:
            - 10909:10909
            - 10911:10911
            - 10912:10912
        volumes:
            - rmqbroker/logs:/home/rocketmq/logs
            - rmqbroker/store:/home/rocketmq/store
        command: sh mqbroker -n namesrv:9876 -c ../conf/broker.conf
        restart: always
        depends_on:
            - namesrv
    rocketmq-console:
        image: apacherocketmq/rocketmq-console:2.0.0
        container_name: rocketmq-console
        environment:
           - JAVA_OPTS= -Drocketmq.namesrv.addr=namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false
        expose:
            - 8080
        restart: always
        depends_on:
            - namesrv
            - broker
volumes:
    rmqnamesrv:
    rmqbroker:
