version: '3'

services:
  elasticsearch:
    image: elasticsearch:${ELASTIC_STACK_VERSION}
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    restart: always
    deploy:
      resources:
        limits:
          memory: 4096M
  skywalking-oap:
    image: apache/skywalking-oap-server:${SKYWALKING_VERSION}
    container_name: skywalking-oap
    environment:
      - SW_STORAGE=elasticsearch
      - SW_STORAGE_ES_CLUSTER_NODES=elasticsearch:9200
    ports:
      - 11800:11800
      - 12800:12800
    depends_on:
      - elasticsearch
    restart: always
    deploy:
      resources:
        limits:
          memory: 4096M
  skywalking-ui:
    image: apache/skywalking-ui:${SKYWALKING_VERSION}
    container_name: skywalking-ui
    environment:
      - SW_OAP_ADDRESS=http://skywalking-oap:12800
#    ports:
#      - 13800:8080
    depends_on:
      - skywalking-oap
    restart: always
    deploy:
      resources:
        limits:
          memory: 4096M