version: '3'
services:
    mysql:
        extends:
            file: mysql.yml
            service: mysql
        volumes:
            - mysql/:/var/lib/mysql/
        restart: always
#
    apollo-portal:
        extends:
            file: apollo.yml
            service: apollo-portal
        restart: always
    apollo-configservice:
        extends:
            file: apollo.yml
            service: apollo-configservice
        restart: always
    apollo-adminservice:
        extends:
            file: apollo.yml
            service: apollo-adminservice
        restart: always
#
    mongo:
        extends:
            file: mongo.yml
            service: mongo
        restart: always
    mongo-express:
        extends:
            file: mongo.yml
            service: mongo-express
        restart: always
#
    redis:
        extends:
            file: redis.yml
            service: redis
        restart: always
    redisinsight:
        extends:
            file: redis.yml
            service: redisinsight
        restart: always
#
    namesrv:
        extends:
            file: rocketmq.yml
            service: namesrv
        restart: always
    broker:
        extends:
            file: rocketmq.yml
            service: broker
        restart: always
    rocketmq-console:
        extends:
            file: rocketmq.yml
            service: rocketmq-console
        restart: always
#
    zookeeper:
        extends:
            file: zookeeper.yml
            service: zookeeper
        restart: always
#
    zipkin:
        extends:
            file: zipkin.yml
            service: zipkin
        restart: always
#
    prometheus:
        extends:
            file: prometheus.yml
            service: prometheus
        restart: always
#
    grafana:
        extends:
            file: grafana.yml
            service: grafana
        restart: always
#
    nginx:
        extends:
            file: nginx.yml
            service: nginx
        restart: always

    sonarqube:
        extends:
            file: sonarqube.yml
            service: sonarqube
        volumes:
            - ./sonarqube/extensions/jdbc-driver/mysql/mysql-connector-java-8.0.21.jar:/opt/sonarqube/extensions/jdbc-driver/mysql/mysql-connector-java-8.0.21.jar
        environment:
            - sonar.jdbc.url=jdbc:mysql://mysql:3306/sonarqube
            - sonar.jdbc.username=root
            - sonar.jdbc.password=
        restart: always
volumes:
    mysql:
