version: '3'
services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    restart: on-failure
#    deploy:
#      resources:
#        limits:
#          memory: 4096M