apiVersion: v1
kind: Namespace
metadata:
  name: mysql
---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: mysql
#spec:
#  resources:
#    requests:
#      storage: 50Gi
#  accessModes:
#    - ReadWriteOnce
#  selector:
#    matchLabels:
#      k8s-app: mysql
#---
### PV
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: mysql
#  namespace: mysql
#  labels:
#    k8s-app: mysql
#spec:
#  capacity:
#    storage: 50Gi
#  accessModes:
#    - ReadWriteOnce
#  mountOptions:
#    - hard
#    - nfsvers=4.1
#  nfs:                     #指定使用 NFS 存储驱动
#    server: 192.168.2.11   #指定 NFS 服务器 IP 地址
#    path: /nfs/mysql       #指定 NFS 共享目录的位置，且需提前在该目录中创建 mysql 目录
#  persistentVolumeReclaimPolicy: Retain
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysql
  labels:
    k8s-app: mysql
spec:
  selector:
    matchLabels:
      k8s-app: mysql
  template:
    metadata:
      labels:
        k8s-app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
          ports:
            - containerPort: 3306
              name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql
  labels:
    k8s-app: mysql
spec:
  type: NodePort
  ports:
    - port: 3306
      nodePort: 3306
  selector:
    k8s-app: mysql